### PR TITLE
Amp fcm

### PR DESCRIPTION
**Pull request by petitJAM**
Bumps it to v1.0.0

### CODE REVIEW

**Comment by petitJAM** [comment]
I think I need to do this too https://developers.google.com/cloud-messaging/android/android-migrate-iid-service

**Comment by petitJAM** [comment]
I should look into this https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#getInstanceId()

This requires me to update google analytics in res_android from 12 to 15, which was hard before for some reason that I don't remember.  It totally worked now, so I think the problem was `google-services.json` which we need now anyway

**Comment by petitJAM** [comment]
Also need to do a bunch of readme updates for all this new stuff.

Some things while I'm thinking about it (not complete list probs):
- `apply plugin: 'com.google.gms.google-services'` in app
- `app/google-services.json` needs to exist

**Comment by Nonsense331** [comment]
🛳

**Pull request merged**
